INSERT INTO theater(name, capacity) VALUES ('Cines UVa', 50);
INSERT INTO theater(name, capacity) VALUES ('Sala Palomitas', 70);
INSERT INTO theater(name, capacity) VALUES ('Multicine Node', 70);
INSERT INTO theater(name, capacity) VALUES ('Cines Villa Sol', 60);
INSERT INTO theater(name, capacity) VALUES ('Blockbuster Cinema', 120);
INSERT INTO theater(name, capacity) VALUES ('Cines Casablanca', 100);
INSERT INTO theater(name, capacity) VALUES ('Festicine', 80);
INSERT INTO movie(name, actors) VALUES ('The Matrix', 'Keanu Reeves, Laurence Fishburne, Carrie-Ann Moss');
INSERT INTO movie(name, actors) VALUES ('The Lord of The Rings', 'Elijah Wood, Ian Mckellen, Viggo Mortensen');
INSERT INTO movie(name, actors) VALUES ('Inception', 'Leonardo DiCaprio');
INSERT INTO movie(name, actors) VALUES ('The Shining', 'Jack Nicholson, Shelley Duvall');
INSERT INTO movie(name, actors) VALUES ('Mission Impossible', 'Tom Cruise, Jeremy Renner');
INSERT INTO movie(name, actors) VALUES ('Terminator', 'Arnold Schwarzenegger, Linda Hamilton');
INSERT INTO movie(name, actors) VALUES ('Titanic', 'Leonardo DiCaprio, Kate Winslet');
INSERT INTO movie(name, actors) VALUES ('Iron Man', 'Robert Downey Jr, Gwyneth Paltrow, Terrence Howard');
INSERT INTO movie(name, actors) VALUES ('Inglorious Bastards', 'Brad Pitt, Diane Kruger');
INSERT INTO movie(name, actors) VALUES ('Million Dollar Baby', 'Hillary Swank, Client Eastwood');
INSERT INTO movie(name, actors) VALUES ('Kill Bill', 'Uma Thurman');
INSERT INTO movie(name, actors) VALUES ('The Hunger Games', 'Jennifer Lawrence');
INSERT INTO movie(name, actors) VALUES ('The Hangover', 'Bradley Cooper, Zach Galifianakis');
INSERT INTO movie(name, actors) VALUES ('Toy Story', 'Tom Hanks, Michael Keaton');
INSERT INTO movie(name, actors) VALUES ('Harry Potter', 'Daniel Radcliffe, Emma Watson');
INSERT INTO movie(name, actors) VALUES ('Avatar', 'Sam Worthington, Sigourney Weaver');
INSERT INTO movie(name, actors) VALUES ('Slumdog Millionaire', 'Anil Kapoor, Dev Patel, Freida Pinto');
INSERT INTO movie(name, actors) VALUES ('The Curious Case of Benjamin Button', 'Brad Pitt, Cate Blanchett');
INSERT INTO movie(name, actors) VALUES ('The Bourne Ultimatum', 'Matt Damon, Julia Stiles');
INSERT INTO movie(name, actors) VALUES ('The Pink Panther', 'Steve Martin, Kevin Kline');
INSERT INTO timeslot(start_time, end_time) VALUES ('18:00', '19:45');
INSERT INTO timeslot(start_time, end_time) VALUES ('20:00', '21:45');
INSERT INTO timeslot(start_time, end_time) VALUES ('22:00', '23:45');
INSERT INTO timeslot(start_time, end_time) VALUES ('00:00', '01:45');
INSERT INTO timeslot(start_time, end_time) VALUES ('02:00', '03:45');
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 1, 1, 1);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 1, 1, 2);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 1, 2, 3);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 1, 3, 3);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-16', 1, 3, 5);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-16', 1, 4, 4);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 1, 5, 5);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-17', 1, 5, 1);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 2, 6, 1);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 2, 7, 2);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 2, 8, 3);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 2, 1, 2);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 2, 2, 3);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 2, 9, 4);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 2, 10, 5);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-16', 3, 11, 1);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 2, 9, 4);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-16', 3, 11, 2);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-16', 3, 12, 2);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-16', 3, 13, 3);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-16', 3, 14, 4);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-16', 3, 15, 5);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-16', 4, 16, 1);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-16', 4, 17, 2);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-16', 4, 18, 3);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-16', 4, 19, 4);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 4, 20, 5);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 5, 1, 1);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 5, 2, 2);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 5, 3, 3);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-18', 5, 4, 4);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-18', 5, 5, 5);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-20', 5, 3, 1);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-21', 5, 4, 4);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-22', 5, 5, 5);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-18', 6, 6, 1);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-18', 6, 7, 2);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-18', 6, 7, 3);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-18', 6, 8, 4);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-18', 6, 8, 3);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-18', 6, 9, 4);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-18', 6, 10, 5);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-18', 7, 11, 1);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-20', 7, 12, 2);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-20', 7, 13, 3);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2023-06-01', 7, 14, 4);
INSERT INTO show_timing(day, theater_id, movie_id, timing_id) VALUES ('2026-03-15', 7, 15, 5);